name: Terraform Plan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::290726015909:role/github-actions-terraform
          aws-region: us-east-1

      - name: Cache .terraform directory
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ./aws-infra/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('aws-infra/.terraform.lock.hcl') }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: Terraform Init
        working-directory: ./aws-infra
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ./aws-infra
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ./aws-infra
        run: terraform plan -no-color 

